name: Integration-Test

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  itest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
        java: [ '11' ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: sbt
      - name: Setup SBT
        uses: sbt/setup-sbt@v1
      - run: |
          sbt "integration/testOnly org.alephium.app.BlocksExportImportTest" &&
          sbt "integration/testOnly org.alephium.app.BroadcastTxTest" &&
          sbt "integration/testOnly org.alephium.app.ConfigTest" &&
          sbt "integration/testOnly org.alephium.app.DanubeUpgradeTest" &&
          sbt "integration/testOnly org.alephium.app.InterCliqueSyncTest" &&
          sbt "integration/testOnly org.alephium.app.IntraCliqueSyncTest" &&
          sbt "integration/testOnly org.alephium.app.MiningTest" &&
          sbt "integration/testOnly org.alephium.app.MultipleInputsTxTest" &&
          sbt "integration/testOnly org.alephium.app.MultisigTest" &&
          sbt "integration/testOnly org.alephium.app.ShutdownTest" &&
          sbt "integration/testOnly org.alephium.app.SweepMiner" &&
          sbt "integration/testOnly org.alephium.app.SweepNoneMiner" &&
          sbt "integration/testOnly org.alephium.app.VotingTest"
        shell: bash
