name: Integration-Test

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  itest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ macos-latest, windows-latest, ubuntu-latest ]
        os: [ windows-latest ]
        java: [ '17' ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: sbt
      - run: |
          N=100
          for i in $(seq 1 $N); do
            sbt 'it:testOnly org.alephium.app.InterCliqueSyncTest'
          done
        shell: bash
